import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import statsRouter from "./stats";
import usersRouter from "./users";
import demandsRouter from "./demands";
import bidsRouter from "./bids";
import ordersRouter from "./orders";
import portfoliosRouter from "./portfolios";
import notificationsRouter from "./notifications";
import authRouter from "./auth";
import postsRouter from "./posts";
import coursesRouter from "./courses";
import adminRouter from "./admin";
import settlementAccountsRouter from "./settlement-accounts";
import paymentCallbackRouter from "./payment-callback";
import downloadRouter from "./download";
import screenRouter from "./screen";
import screenVideosRouter from "./screen-videos";
import activitiesRouter from "./activities";
import agentRouter from "./agent";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(storageRouter);
router.use(statsRouter);
router.use(usersRouter);
router.use(demandsRouter);
router.use(bidsRouter);
router.use(ordersRouter);
router.use(portfoliosRouter);
router.use(notificationsRouter);
router.use(postsRouter);
router.use(coursesRouter);
router.use(adminRouter);
router.use(settlementAccountsRouter);
router.use(paymentCallbackRouter);
router.use(downloadRouter);
router.use(screenRouter);
router.use(screenVideosRouter);
router.use(activitiesRouter);
router.use(agentRouter);

export default router;
