import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import statsRouter from "./stats";
import usersRouter from "./users";
import portfoliosRouter from "./portfolios";
import notificationsRouter from "./notifications";
import authRouter from "./auth";
import postsRouter from "./posts";
import coursesRouter from "./courses";
import adminRouter from "./admin";
import settlementAccountsRouter from "./settlement-accounts";
import paymentCallbackRouter from "./payment-callback";
import downloadRouter from "./download";
import screenRouter from "./screen";
import screenVideosRouter from "./screen-videos";
import activitiesRouter from "./activities";
import agentRouter from "./agent";
import catCategoriesRouter from "./cat-categories";
import v2Router from "./v2/index";
import contestsRouter from "./contests";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(storageRouter);
router.use(statsRouter);
router.use(usersRouter);
router.use(portfoliosRouter);
router.use(notificationsRouter);
router.use(postsRouter);
router.use(coursesRouter);
router.use(adminRouter);
router.use(settlementAccountsRouter);
router.use(paymentCallbackRouter);
router.use(downloadRouter);
router.use(screenRouter);
router.use(screenVideosRouter);
router.use(activitiesRouter);
router.use(agentRouter);
router.use(catCategoriesRouter);
router.use(contestsRouter);
router.use("/v2", v2Router);

export default router;
