// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pub-profile/VariantA.tsx": () => import("../components/mockups/pub-profile/VariantA.tsx"),
  "./components/mockups/pub-profile/VariantB.tsx": () => import("../components/mockups/pub-profile/VariantB.tsx"),
  "./components/mockups/screen-design/NewStyle.tsx": () => import("../components/mockups/screen-design/NewStyle.tsx")
};
